### ISSUE TITLE
about the parameters of R , d, and Xw of fisheye image transform algorithm

### ISSUE THREAD

**Issue by simonyang0608** [benmaier/python-fisheye#3]
Did anyone know the definition and unit of R, d, and Xw?, and did all of them in the unit based on the pixels or not?

**Comment by benmaier** [comment]
R is in unit of pixels, x_w is in relative units between zero and R (i.e. 0 <= x_w <= 1), d is a positive number (dimensionless) that quantifies the strength of the magnification around the focal point. I suggest you check out this interactive text to understand their meaning: https://observablehq.com/@benmaier/a-visually-more-appealing-fisheye-function

**Comment by simonyang0608** [comment]
> R is in unit of pixels, x_w is in relative units between zero and R (i.e. 0 <= x_w <= 1), d is a positive number (dimensionless) that quantifies the strength of the magnification around the focal point. I suggest you check out this interactive text to understand their meaning: https://observablehq.com/@benmaier/a-visually-more-appealing-fisheye-function
